name: Deploy to Amazon ECS

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: ap-northeast-2
  S3BUCKET: github-actions-deploy-react

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "19.4.0"
          cache: "yarn"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      - name: Copy appspec.yml to build folder
        run: cp appspec.yml build/

      - name: Make a zip file
        run: zip -r build-${{ github.sha }}.zip build/

      - name: Upload versioned build.zip to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp build-${{ github.sha }}.zip s3://${{ env.S3BUCKET }}/blog/build-${{ github.sha }}.zip

      - name: Create AWS CodeDeploy deployment
        run: |
          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --application-name blog-react \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name blog-react-deploy-group-1 \
            --s3-location bucket=${{ env.S3BUCKET }},bundleType=zip,key=blog/build-${{ github.sha }}.zip \
            --query "deploymentId" \
            --output text)

          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
